version: '3.8'

services:
  # LibreChat with MCP integration
  librechat:
    image: ghcr.io/danny-avila/librechat-dev:latest
    ports:
      - "3081:3080"
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml:ro
      - ./mcp-config.json:/app/api/mcp-config.json:ro
      - librechat_data:/app/client/public/images
    depends_on:
      - mongodb
      - redis
    networks:
      - chat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MongoDB for LibreChat
  mongodb:
    image: mongo:7.0
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=librechat
    networks:
      - chat-network

  # Redis for LibreChat
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - chat-network

volumes:
  mongodb_data:
  redis_data:
  librechat_data:

networks:
  chat-network:
    driver: bridge